#!/bin/sh
##
# cmus-notify -- based on cmus-status-display
# author: nblock <nblock [at] archlinux [dot] us>
# version: git
# license: GPLv2
##
# a simple script to display cmus' status inside awesome with awesome-client
#
# in cmus: ":set status_display_program=/path/to/cmus-notify" to activate the script
##

output()
{
	echo "$*" |awesome-client 2>&1
}

while test $# -ge 2
do
	eval _$1='$2'
	shift
	shift
done

START="cmuswidget:set_markup(\"<span foreground='orange'>music: </span><span foreground='green'>"
END='</span>")'

if test -n "$_file"
then
	h=$(($_duration / 3600))
	m=$(($_duration % 3600))

	duration=""
	test $h -gt 0 && dur="$h:"
	duration="$dur$(printf '%02d:%02d' $(($m / 60)) $(($m % 60)))"

	output "${START}[$_status] $_artist - $_title - $_album ($_date) [$duration]${END}"
elif test -n "$_url"
then
	output "${START}[$_status] $_url - $_title${END}"
else
	output "${START}[$_status]${END}"
fi
